apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
  namespace: simplyfi
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - port: 8080        # service port inside cluster
      targetPort: 8080  # container port in api pod
      nodePort: 30081   # external port on the node
